// Code generated by fastssz. DO NOT EDIT.
// Hash: ab3f6c3d731a752a6b6cc228717e26ace88253e8049d39e20d5777e79973e514
// Version: 0.1.3
package capella

import (
	"github.com/attestantio/go-eth2-client/spec/capella"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the ExecutionPayloadWithdrawals object
func (e *ExecutionPayloadWithdrawals) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionPayloadWithdrawals object to a target array
func (e *ExecutionPayloadWithdrawals) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Withdrawals'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(e.Withdrawals) * 44

	// Field (0) 'Withdrawals'
	if size := len(e.Withdrawals); size > 8 {
		err = ssz.ErrListTooBigFn("ExecutionPayloadWithdrawals.Withdrawals", size, 8)
		return
	}
	for ii := 0; ii < len(e.Withdrawals); ii++ {
		if dst, err = e.Withdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionPayloadWithdrawals object
func (e *ExecutionPayloadWithdrawals) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Withdrawals'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Withdrawals'
	{
		buf = tail[o0:]
		num, err := ssz.DivideInt2(len(buf), 44, 8)
		if err != nil {
			return err
		}
		e.Withdrawals = make([]*capella.Withdrawal, num)
		for ii := 0; ii < num; ii++ {
			if e.Withdrawals[ii] == nil {
				e.Withdrawals[ii] = new(capella.Withdrawal)
			}
			if err = e.Withdrawals[ii].UnmarshalSSZ(buf[ii*44 : (ii+1)*44]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionPayloadWithdrawals object
func (e *ExecutionPayloadWithdrawals) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Withdrawals'
	size += len(e.Withdrawals) * 44

	return
}

// HashTreeRoot ssz hashes the ExecutionPayloadWithdrawals object
func (e *ExecutionPayloadWithdrawals) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionPayloadWithdrawals object with a hasher
func (e *ExecutionPayloadWithdrawals) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Withdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Withdrawals))
		if num > 8 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Withdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 8)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ExecutionPayloadWithdrawals object
func (e *ExecutionPayloadWithdrawals) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(e)
}
